### ISSUE TITLE
Add documentation for adding extensions

### ISSUE THREAD

**Issue by colinrobinsonuib** [wmde/wikibase-release-pipeline#807]
In my `deploy/` folder I created a folder called `extensions/` where I put some extensions (e.g. WikibaseQualityConstraints).

I then created `docker-compose.override.yml` that looks like:

```
services:
  wikibase:
    volumes:
      - ./extensions:/extensions:ro
    entrypoint: >
      sh -c "cp -r /extensions/* /var/www/html/extensions/ && /bin/bash /entrypoint.sh"
```

I feel like this would be something nice to put in the README for new people.
